### ISSUE TITLE
Issue with png R package

### ISSUE THREAD

**Issue by perkaer** [s-u/png#3]
Hi all

I installed the newest version of ggmap from CRAN and get the following error.

```R
> R.Version()
$platform
[1] "x86_64-apple-darwin14.0.0"

$arch
[1] "x86_64"

$os
[1] "darwin14.0.0"

$system
[1] "x86_64, darwin14.0.0"

$status
[1] ""

$major
[1] "3"

$minor
[1] "1.2"

$year
[1] "2014"

$month
[1] "10"

$day
[1] "31"

$`svn rev`
[1] "66913"

$language
[1] "R"

$version.string
[1] "R version 3.1.2 (2014-10-31)"

$nickname
[1] "Pumpkin Helmet"

> sunMap <- get_map(location = 'Copenhagen')
Map from URL : http://maps.googleapis.com/maps/api/staticmap?center=Copenhagen&zoom=10&size=640x640&scale=2&maptype=terrain&language=en-EN&sensor=false
Error in readPNG(tmp) : unable to initialize libpng
In addition: Warning message:
In readPNG(tmp) :
  libpng warning: Application built with libpng-1.6.16 but running with 1.5.17
```

I tried deleting the png package and letting ggmap install it as a dependency, but same result. It should be mentioned that I have libpng version 1.6.16 installed via macports.

Any help is greatly appreciated!

Best,
Per

**Comment by s-u** [comment]
As the error says you have libpng version mismatch. Obviously, your R is NOT the CRAN R so you cannot use CRAN binaries.

**Comment by perkaer** [comment]
Ah ok, deleted my macports R and used the CRAN. Now it works, thanks alot :)

**Comment by brunoasm** [comment]
Hi all, I ran into the same problem (OS X El Capitan 10.11.4, R 3.2.4). I tried to deactivate macports R and install CRAN R. I did not solve the problem in my case.

**Comment by s-u** [comment]
Check your `.libPaths()` - apparently you have a bad build somewhere. If in doubt, re-install `png` from CRAN.

**Comment by brunoasm** [comment]
Thanks for the suggestion!
It turns out I just had to reinstall the package after deactivating
macports R. Now it works perfectly.

2016-04-13 13:41 GMT-04:00 Simon Urbanek <notifications@github.com>:
